= SecReq 3.65 - Linux OS for Servers
:author_name: Markus Schumburg (Telekom Security)
:author_email: security.automation@telekom.de
:revnumber: 0.1
:revdate: 26-10-2018
:revremark: draft
:imagesdir: ./images

:sectlinks:
== 1. Basic Hardening

:sectlinks:
==== Req 1: Unused services and protocols must be deactivated.

After installation of systems and software products local or remote reachable services and protocols may be active, which are not necessarily needed for operation and functionality of the system. These include also services and protocols which may not be used in Deutsche Telekom Group networks due to known security vulnerabilities. Such services and protocols must be completely disabled on the system. Additionally, it is important that protocols and service are still deactivated after system re-boot.

This kind of system hardening must be done before the system is reachable from the network. Otherwise an attacker has the possibility to attack and maybe compromise the unsecured system.

_Motivation:_ Services and protocols that are not required for system operation increase the potential attack sur-face and thus the risk of the system being compromised. This risk is further increased by the fact that a security inspection and appropriate optimization of the configuration for unused services and protocols is not being done in most cases.

*Implementation* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 12)

----
   test
----

[cols="1",width=100%,frame="topbot",grid="none"]
|===
| *Audit* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 12)
|===
