= Telekom Security Compliance Framework
:author_name: Markus Schumburg (Telekom Security)
:author_email: security.automation@telekom.de
:revnumber: 0.1
:revdate: 26-10-2018
:revremark: draft
:imagesdir: ./images

:sectlinks:

== Linux OS for Servers
===	1. Introduction
Linux is a popular operating system for server systems. It is used from single bare metal servers to high scaling cloud environments.

This documents includes examples for technical implementation and compliance checks for the security requirements of https://security.telekom.com/[Telekom Security] for Linux OS for servers.

The examples in this document are tested for the following Linux distributions:

   * [*] Ubuntu LTS 14.04
   * [*] Ubuntu LTS 16.04
   * [*] Ubuntu LTS 18.04
   * [*] RedHat Enterprise Linux 7.x (RHEL)
   * [*] Suse Linux Enterprise Server 12 (SLES)

==== 1.1 Scope
In scope of this is document are server systems with Linux OS. This includes the following types of servers:

* bare metal servers
* virtualized servers (VMs)
* virtualization hosts

==== 1.2 Not in Scope
This document is not intended to be used for workstations with Linux OS and container images based on Linux. Because of different use cases, associated threats and needed software, workstations need another set of requirements. Container images have to be treated differently as they normally do not include a full Linux OS.

---
=== Content

   1. link:https://github.com/telekomsecurity/TelekomSecurity.Compliance.Framework/blob/master/secreq%203.65%20linux%20os/linux.(01)introduction.adoc#1-introduction[Introduction]
   2. link:https://github.com/telekomsecurity/TelekomSecurity.Compliance.Framework/blob/master/secreq%203.65%20linux%20os/linux.(02)basic-hardening.adoc[Basic Hardening]
