= Telekom Security Compliance Framework
:author_name: Markus Schumburg (Telekom Security)
:author_email: security.automation@telekom.de
:revnumber: 0.1
:revdate: 26-10-2018
:revremark: draft
ifdef::env-github[]
:imagesdir: ./images
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:
:toclevels: 5


:sectlinks:

== Linux OS for Servers - 3	Logging

[#req365-30]
==== Req 30:	Logging must be enabled in bootloader configuration.

It is important to configure logging during system boot in grub.cfg to ensure the logging of security events before auditd daemon is started.

_Motivation:_ Logging security-relevant events is a basic requirement for detecting ongoing attacks as well as at-tacks that have already occurred. This is the only way in which suitable measures can be taken to maintain or restore system security. Logging data could be used as evidence to take legal steps against attackers.

*Compliance Check* (all)

Use the following command to check grub configuration in file '/etc/default/grub':
----
   grep -i "GRUB_CMDLINE_LINUX=" /etc/default/grub
----
Expected output: GRUB_CMDLINE_LINUX="audit=1"

*Implementation* (all)

Add the following line to the file '/etc/default/grub'
----
   GRUB_CMDLINE_LINUX="audit=1"
----

Grub must be reloaded after configuration has changed with the following command:

*Ubuntu Linux*
----
  # update-grub
----

*RedHat & Suse Linux*
----
  # grub2-mkconfig -o /boot/grub2/grub.cfg
----

[#req365-31]
==== Req 31:	Log rotation for logfiles must be configured.

Log rotation for logfiles must be enabled. Files must be rotated based on file size and max lifetime of file.

_Motivation:_ An attacker can trigger log events to fill up the disk space of the server. This could lead to a denial of service of the server.

*Compliance Check* (all)

Check the file '/etc/logrotate.conf' for correct parameters for default configuration
with following commands:

Value in which interval log files should be rotated.
----
   # grep -i <logrotate-time> /etc/logrotate.conf
----
Possible outputs: daily, weekly, monthly  (recommended weekly)

Value how many times should be rotated before oldest file will be deleted.
----
  # grep -i "^rotate" /etc/logrotate.conf
----
Recommended value: 4

Additionally must be checked if the execution of logrotate will be done on a daily
basis. Check folder '/etc/cron.daily' with the following command:
----
  # ls -la logrotate
----
Expected output (beside existents of file check priviledges, user and group):
-rwxr-xr-x 1 root root 372 Jan 22  2014 logrotate

NOTE: Additional specific configurations can be found in files located in directory
'logrotate.d/'.

*Implementation* (all)

The following entries must be added to file '/etc/logrotate.conf':
----
   weekly
   rotate 4
----

Additionally specific configurations can be changed in file '/etc/logrotate.conf'
and files in folder 'logrotate.d/' if needed.

Example:
----
/var/log/wtmp {
    missingok
    **monthly**
    create 0660 root utmp
    **maxsize 10**
    rotate **1**
}
----

[#req365-32]
==== Req 32:	System time must be synchronized against a reference time source.

A service like NTP (client programs: ntp, crony) must be used for time synchronization. Example for Deutsche Telekom AG NTP server pools are:

*	ntp-pool-info_ntpp10.telekom.de
*	ntp-pool-info_ntpp21.telekom.de

_Motivation:_ Time synchronization must be done on a server to support time sensitive security mechanisms like the usage of certificates or solutions like Kerberos. A precise time is also mandatory to ensures con-sistent time records for logging events.

*Compliance Check* (all)

Check with the following command if time synchronization is enabled:
----
  # timedatectl
----
Expected output (example): Command shows if time is synchronization (NTP synchronized). +
----
Local time: Mon 2019-02-04 15:50:50 CET
  Universal time: Mon 2019-02-04 14:50:50 UTC
        RTC time: Mon 2019-02-04 14:50:49
        Timezone: Europe/Berlin (CET, +0100)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: no
----

*Compliance Check* (Ubuntu LTS 14.04)

Ubuntu 14.04 uses ntpd for time synchronization.

To check if time is synchronized with correct NTP server use the following command:
----
  # netq -p
----
Expected output (example):
----
remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
ntp1.sul.t-onli 172.20.96.197    2 u   53   64    1    9.419  -17.683   0.000
----

*Compliance Check* (Ubuntu LTS 16.04/18.04)

Ubuntu 16.04 and 18.04 uses 'timesyncd' as default time synchronization. It works in
the in lightweight way to synchronize system time.

To check the status of time synchronization use:
----
  # systemctl status systemd-timesyncd.service
----
Expected output - check for following line in output:
Status: "Synchronized to time server 194.25.134.196:123 (ntp1.t-online.de)."

*Compliance Check* (RedHat & Suse)

Use the following command to check the status of chronyd:
----
  # systemctl status chronyd -l
----
Expected output: 'active' if chrony is running properly.

Use the following command to check chrony sources:
----
  # chronyc sources
----
Expected output (example):
----
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^* ntp1.sul.t-online.de          2   6    37    41   +133us[ +320us] +/-   50ms
----

*Implementation* (Ubuntu LTS 14.04)

*Implementation* (Ubuntu LTS 16.04/18.04)

*Implementation* (RedHat & Suse)

----
   <tbd>implementation
----

=== 3.1	Auditd

The auditd subsystem is an access monitoring and accounting for Linux. It can be used to define granular log events to be monitored under Linux OS. From security point of view log events can be used to detect malicious activities and to analyze possible breaches.

[#req365-33]
==== Req 33:	Auditd service must be used to log security relevant events.

On Linux server, the auditd daemon must be installed and configured to log security events. Every security event must be logged with a precise timestamp and a unique system reference.

_Motivation:_ Logging security-relevant events is a basic requirement for detecting ongoing attacks as well as at-tacks that have already occurred. This is the only way in which suitable measures can be taken to maintain or restore system security. Logging data could be used as evidence to take legal steps against attackers.

*Compliance Check* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>Compliance Check
----

*Implementation* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>implementation
----

[#req365-34]
==== Req 34:	System events must be logged.

On Linux servers, the following System events must be logged:

[cols="30,60,10",options="header"]
|===
|Event Type
|Description
|Category

|System Startup and Shut-down
|All restarts or shutdowns of the OS must be logged.
|Mandatory
|(Un)Installation of software
|After the commissioning of the server, every uninstallation and installation of software must be logged.
|Mandatory
|Change of system time
|Modification of the local system time and change of ntp settings must be logged.
|Mandatory
|Connection of external device (storage)
|The connection of external devices like USB-Flash drives, which can mount on the running server, must be logged.
|Mandatory
|Privileged commands execution
|The use of privileged commands with SUID/SGID must be logged.
|Mandatory
|Loading/unloading of kernel modules
|The loading and unloading of kernel module must be logged.
|Mandatory
|Change of scheduled jobs
|Jobs which are executed periodically, must be monitored, if they are changed or deleted.
|Optional
|===

_Motivation:_ It is unusual to make system changes when the OS is put into operation. An attacker who has access to the server could change the system for its malicious purpose. The logging of the system events is necessary to detect and backtrack these attacks.

*Compliance Check* (Ubuntu LTS (14.04/16.04/18.04), RedHat, Suse)

----
   <tbd>Compliance Check
----

*Implementation* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>implementation
----

[#req365-35]
==== Req 35:	Access and Authentication events must be logged.

On Linux servers, the following Access and Authentication events must be logged:

[cols="30,60,10",options="header"]
|===
|Event Type
|Description
|Category

|Logon and Logoff
|The Logon and Logoff of a User via external or local access must be logged.
|Mandatory
|Password Change
|User Password changes or resets must be logged.
|Mandatory
|Account Expiration
|It must be logged when an account expires.
|Mandatory
|Account Lockout / Reactivation
|It must be logged, if an account will be locked or reactivated.
|Mandatory
|Escalation of privileges
|It must be logged, if a user with administrator equivalent rights logs on.
|Mandatory
|===

_Motivation:_ The logging of authentication and access events can be useful to backtrack who has access to a certain time.
With these logs it is for example possible to detect a captured account which is used by an attacker.

*Compliance Check* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>Compliance Check
----

*Implementation* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>implementation
----

[#req365-36]
==== Req 36:	Account and Group Management events must be logged.

On Linux servers, the following Account and Group Management events must be logged:

[cols="30,60,10",options="header"]
|===
|Event Type
|Description
|Category

|Create User
|If a new user is created, it must be logged.
|Mandatory
|Modify User
|If a user is modified (e.g. Membership, User rights), it must be logged.
|Mandatory
|Delete User
|If a user is deleted, it must be logged.
|Mandatory
|Create Group
|If a new group is created, it must be logged.
|Mandatory
|Modify Group
|If a group is modified (e.g. Members, Group Rights), it must be logged.
|Mandatory
|Delete Group
|If a group is deleted, it must be logged.
|Mandatory
|===

_Motivation:_ The logging of account and group management events can be useful to backtrack user and group management.
With these logs it is possible to detect malicious modification, creation and deletion of users and groups.

*Compliance Check* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>Compliance Check
----

*Implementation* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>implementation
----

[#req365-37]
==== Req 37:	Configuration Change events must be logged.

On Linux servers, the following Configuration Change events must be logged:

[cols="30,60,10",options="header"]
|===
|Event Type
|Description
|Category

|Disable logging
|It must be logged, if the logging service is disabled.
|Mandatory
|Deletion and unauthorized modification of logs
|The deletion of events must be logged. The unauthorized modification of logs must be logged.
|Mandatory
|Change of logging configuration
|It must be logged, if there is a change of the logging configuration.
|Mandatory
|Authentication Subsystem changes
|Changes of Authentication Subsystems (e.g. LDAP- or Kerberos-Policy) must be logged.
|Optional
|Security Subsystem change
|Changes of Security Subsystems shall be logged.
|Optional
|Backup configuration change
|It shall be logged, if there is a change of the backup con-figuration.
|Optional
|OS FW configuration change
|The change of the OS Firewall configuration shall be logged.
|Optional
|Critical Registry/Flags/File changes
|Depending on the use case, critical registry--, flags- or file-changes should be logged.
|Optional
|===

_Motivation:_ Configuration changes could have a massive impact of the OS and consequently could be a security risk.
It is necessary to identify all important configurations on the OS and log the changes.

*Compliance Check* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>Compliance Check
----

*Implementation* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>implementation
----

[#req365-38]
==== Req 38:	Auditd configuration must be immutable.

Immutable mode must be set for auditd to avoid that audit rules can be modified with 'auditctl' command.

_Motivation:_ If auditd is not in immutable mode, unauthorized users can initiate changes to hide malicious activity.

*Compliance Check* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>Compliance Check
----

*Implementation* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>implementation
----

=== 3.2	External Logging

[#req365-39]
==== Req 39:	Security relevant logging data must be send to an external system direct after their creation.

Security relevant logging data must be forwarded to a logging server as soon as possible after their creation. Logging solutions like rsyslog or syslog-ng can be used.

_Motivation:_ If logging data is only stored locally, it can be manipulated by an attacker to conceal the attack and any manipulation done on the system. This is the reason why the events must be forwarded immedi-ately after occurrence.

*Compliance Check* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>Compliance Check
----

*Implementation* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>implementation
----

==== 3.2.1	RSyslog

[#req365-40]
==== Req 40:	If RSyslog is used, the default permission of 640 or more restrictive for logfiles must be configured.

For RSyslog the default permissions of 640 or more restrictive used for new generated logging files must be configured in file 'rsyslog.conf'.

_Motivation:_ Unauthorized access to logging files is possible if they have wrong file permissions. This is a risk of unwanted information leakage, as such files can contain sensitive information.

*Compliance Check* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>Compliance Check
----

*Implementation* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>implementation
----

[#req365-41]
==== Req 41:	If RSyslog is used, at least one central logging server must be configured.

One or several external log servers must be configured in RSyslog configuration.

_Motivation:_ If logging data is only stored locally, it can be manipulated by an attacker to conceal the attack and any manipulation done on the system. This is the reason why the events must be forwarded immedi-ately after occurrence.

*Compliance Check* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>Compliance Check
----

*Implementation* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   <tbd>implementation
----

==== 3.2.2	Syslog-NG

[#req365-42]
==== Req 42:	If Syslog-NG is used, the default permission of 640 or more restrictive for logfiles must be configured.

For Syslog-NG the default permissions of 640 or more restrictive used for new generated logging files must be configured in file 'syslog-ng.conf'.

_Motivation:_ Unauthorized access to logging files is possible if they have wrong file permissions. This is a risk of unwanted information leakage, as such files can contain sensitive information.

*Compliance Check* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   _(tbd) will be implemented in future version of document_
----

*Implementation* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   _(tbd) will be implemented in future version of document_
----

[#req365-43]
==== Req 43:	If Syslog-NG is used, at least one central logging server must be configured.

One or several external log servers must be configured in RSyslog configuration.

_Motivation:_ If logging data is only stored locally, it can be manipulated by an attacker to conceal the attack and any manipulation done on the system. This is the reason why the events must be forwarded immedi-ately after occurrence.

*Compliance Check* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   _(tbd) will be implemented in future version of document_
----

*Implementation* (Ubuntu LTS (14.04/16.04/18.04), RHEL 7.x, SLES 15)

----
   _(tbd) will be implemented in future version of document_
----

---
=== Content

   1. link:https://github.com/telekomsecurity/TelekomSecurity.Compliance.Framework/blob/master/Linux%20OS%20for%20Servers%20(3.65)/linux.(01)introduction.adoc#1-introduction[Introduction]
   2. link:https://github.com/telekomsecurity/TelekomSecurity.Compliance.Framework/blob/master/Linux%20OS%20for%20Servers%20(3.65)/linux.(02)basic-hardening.adoc[Basic Hardening]
   3. link:https://github.com/telekomsecurity/TelekomSecurity.Compliance.Framework/blob/master/Linux%20OS%20for%20Servers%20(3.65)/linux.(03)Logging.adoc[Logging]
   4. link:https://github.com/telekomsecurity/TelekomSecurity.Compliance.Framework/blob/master/Linux%20OS%20for%20Servers%20(3.65)/linux.(04)pam.adoc[Pluggable Authentication Modules]
   5. link:https://github.com/telekomsecurity/TelekomSecurity.Compliance.Framework/blob/master/Linux%20OS%20for%20Servers%20(3.65)/linux.(05)iptables.adoc[IPTables]
   6. link:https://github.com/telekomsecurity/TelekomSecurity.Compliance.Framework/blob/master/Linux%20OS%20for%20Servers%20(3.65)/linux.(06)mac.adoc[Mandatory Access Control]
   7. link:https://github.com/telekomsecurity/TelekomSecurity.Compliance.Framework/blob/master/Linux%20OS%20for%20Servers%20(3.65)/linux.(07)compliance-checks.adoc[Regular Compliance Checks]
